package de.traum.traum.widget

data class WidgetSlotDef(val label: String, val valueKey: String, val goalKey: String?)
data class WidgetCatalogDef(
    val key: String,
    val title: String,
    val groupLabel: String,
    val accentHex: String,
    val template: String,
    val route: String,
    val slots: List<WidgetSlotDef>,
)

object WidgetCatalog {
    val tabs = listOf(
        WidgetCatalogDef(
            key = "overview",
            title = "Übersicht",
            groupLabel = "Allgemein",
            accentHex = "#FF6B3D",
            template = "overview",
            route = "/home",
            slots = listOf(
            WidgetSlotDef("Schritte", "health.steps", "health.stepsGoal"),
            WidgetSlotDef("Kalorien", "nutrition.kcal", "nutrition.kcalGoal"),
            WidgetSlotDef("Wasser", "nutrition.waterMl", "nutrition.waterGoalMl"),
            WidgetSlotDef("Aufgabe", "planning.nextTodo", null),
            ),
        ),
        WidgetCatalogDef(
            key = "health",
            title = "Gesundheit",
            groupLabel = "Gesundheit",
            accentHex = "#F43F5E",
            template = "overview",
            route = "/health",
            slots = listOf(
            WidgetSlotDef("Score", "health.score", null),
            WidgetSlotDef("Schlaf", "health.sleepHours", null),
            WidgetSlotDef("Puls", "health.heartRate", null),
            WidgetSlotDef("Aktiv", "health.activeMinutes", null),
            ),
        ),
        WidgetCatalogDef(
            key = "nutrition",
            title = "Ernährung",
            groupLabel = "Ernährung",
            accentHex = "#3DD68C",
            template = "overview",
            route = "/nutrition",
            slots = listOf(
            WidgetSlotDef("Kalorien", "nutrition.kcal", "nutrition.kcalGoal"),
            WidgetSlotDef("Protein", "nutrition.protein", "nutrition.proteinGoal"),
            WidgetSlotDef("Wasser", "nutrition.waterMl", "nutrition.waterGoalMl"),
            WidgetSlotDef("Mahlzeit", "nutrition.lastMeal", null),
            ),
        ),
        WidgetCatalogDef(
            key = "training",
            title = "Training",
            groupLabel = "Training",
            accentHex = "#5B6CF9",
            template = "overview",
            route = "/training",
            slots = listOf(
            WidgetSlotDef("Nächstes", "training.nextWorkout", null),
            WidgetSlotDef("Volumen", "training.weeklyVolume", null),
            WidgetSlotDef("Streak", "training.streak", null),
            ),
        ),
        WidgetCatalogDef(
            key = "planning",
            title = "Planung",
            groupLabel = "Planung",
            accentHex = "#F5A623",
            template = "overview",
            route = "/planning",
            slots = listOf(
            WidgetSlotDef("Offen", "planning.openTodos", null),
            WidgetSlotDef("Termin", "planning.nextAppointment", null),
            WidgetSlotDef("Habits", "planning.habitsDone", "planning.habitsTotal"),
            WidgetSlotDef("Medis", "planning.medsDone", "planning.medsTotal"),
            ),
        ),
        WidgetCatalogDef(
            key = "budget",
            title = "Budget",
            groupLabel = "Budget",
            accentHex = "#00D4D4",
            template = "overview",
            route = "/budget",
            slots = listOf(
            WidgetSlotDef("Saldo", "budget.balanceMonth", null),
            WidgetSlotDef("Ausgaben", "budget.spent", "budget.limit"),
            WidgetSlotDef("Einnahmen", "budget.income", null),
            WidgetSlotDef("Top", "budget.topCategory", null),
            ),
        ),
        WidgetCatalogDef(
            key = "diary",
            title = "Tagebuch",
            groupLabel = "Tagebuch",
            accentHex = "#9B8EC4",
            template = "overview",
            route = "/diary",
            slots = listOf(
            WidgetSlotDef("Streak", "diary.writeStreak", null),
            WidgetSlotDef("Letzter", "diary.lastEntry", null),
            WidgetSlotDef("Monat", "diary.entriesThisMonth", null),
            ),
        ),
        WidgetCatalogDef(
            key = "abstinence",
            title = "Abstinenz",
            groupLabel = "Abstinenz",
            accentHex = "#FFAA55",
            template = "overview",
            route = "/abstinence",
            slots = listOf(
            WidgetSlotDef("Titel", "abstinence.title", null),
            WidgetSlotDef("Dauer", "abstinence.duration", null),
            WidgetSlotDef("Gespart", "abstinence.moneySaved", null),
            ),
        ),
        WidgetCatalogDef(
            key = "substances",
            title = "Mittel",
            groupLabel = "Mittel",
            accentHex = "#0099BB",
            template = "overview",
            route = "/substances",
            slots = listOf(
            WidgetSlotDef("Zuletzt", "substances.lastIntake", null),
            WidgetSlotDef("Heute", "substances.takenToday", null),
            ),
        ),
        WidgetCatalogDef(
            key = "period",
            title = "Zyklus",
            groupLabel = "Zyklus",
            accentHex = "#FF8FAB",
            template = "overview",
            route = "/period",
            slots = listOf(
            WidgetSlotDef("Zyklustag", "period.cycleDay", null),
            WidgetSlotDef("Phase", "period.phase", null),
            WidgetSlotDef("Nächste", "period.nextDays", null),
            ),
        ),
        WidgetCatalogDef(
            key = "notes",
            title = "Notizen",
            groupLabel = "Notizen",
            accentHex = "#9B8EC4",
            template = "overview",
            route = "/notes",
            slots = listOf(
            WidgetSlotDef("Notizen", "notes.count", null),
            WidgetSlotDef("Letzte", "notes.lastNote", null),
            ),
        ),
        WidgetCatalogDef(
            key = "map",
            title = "Karte",
            groupLabel = "Karte",
            accentHex = "#3DD68C",
            template = "overview",
            route = "/graffitimap",
            slots = listOf(
            WidgetSlotDef("Orte", "map.placesCount", null),
            WidgetSlotDef("Foto", "map.lastPhoto", null),
            ),
        ),
    )
    val functions = listOf(
        WidgetCatalogDef(
            key = "clockDate",
            title = "Uhr",
            groupLabel = "Allgemein",
            accentHex = "#FF6B3D",
            template = "stat",
            route = "/home",
            slots = listOf(
            WidgetSlotDef("Datum", "general.clockDate", null),
            ),
        ),
        WidgetCatalogDef(
            key = "weatherNow",
            title = "Wetter",
            groupLabel = "Allgemein",
            accentHex = "#FF6B3D",
            template = "stat",
            route = "/home",
            slots = listOf(
            WidgetSlotDef("Temperatur", "general.weatherTemp", null),
            ),
        ),
        WidgetCatalogDef(
            key = "weatherForecast",
            title = "Wetter",
            groupLabel = "Allgemein",
            accentHex = "#FF6B3D",
            template = "stat",
            route = "/home",
            slots = listOf(
            WidgetSlotDef("Vorhersage", "general.weatherForecast", null),
            ),
        ),
        WidgetCatalogDef(
            key = "appFavorites",
            title = "Apps",
            groupLabel = "Allgemein",
            accentHex = "#FF6B3D",
            template = "list",
            route = "/home",
            slots = listOf(
            WidgetSlotDef("Favoriten", "general.appFavorites", null),
            ),
        ),
        WidgetCatalogDef(
            key = "quickActions",
            title = "Schnellzugriff",
            groupLabel = "Allgemein",
            accentHex = "#FF6B3D",
            template = "list",
            route = "/home",
            slots = listOf(
            WidgetSlotDef("Aktionen", "general.quickActions", null),
            ),
        ),
        WidgetCatalogDef(
            key = "dailyScore",
            title = "Tagesübersicht",
            groupLabel = "Allgemein",
            accentHex = "#FF6B3D",
            template = "stat",
            route = "/home",
            slots = listOf(
            WidgetSlotDef("Score", "health.score", null),
            ),
        ),
        WidgetCatalogDef(
            key = "miniCalendar",
            title = "Kalender",
            groupLabel = "Allgemein",
            accentHex = "#FF6B3D",
            template = "list",
            route = "/home",
            slots = listOf(
            WidgetSlotDef("Termin", "planning.nextAppointment", null),
            ),
        ),
        WidgetCatalogDef(
            key = "steps",
            title = "Schritte",
            groupLabel = "Gesundheit",
            accentHex = "#F43F5E",
            template = "progress",
            route = "/health",
            slots = listOf(
            WidgetSlotDef("Schritte", "health.steps", "health.stepsGoal"),
            ),
        ),
        WidgetCatalogDef(
            key = "sleep",
            title = "Schlaf",
            groupLabel = "Gesundheit",
            accentHex = "#F43F5E",
            template = "stat",
            route = "/health",
            slots = listOf(
            WidgetSlotDef("Stunden", "health.sleepHours", null),
            ),
        ),
        WidgetCatalogDef(
            key = "heartRate",
            title = "Herzfrequenz",
            groupLabel = "Gesundheit",
            accentHex = "#F43F5E",
            template = "stat",
            route = "/health",
            slots = listOf(
            WidgetSlotDef("Puls", "health.heartRate", null),
            ),
        ),
        WidgetCatalogDef(
            key = "moodToday",
            title = "Stimmung",
            groupLabel = "Gesundheit",
            accentHex = "#F43F5E",
            template = "stat",
            route = "/health",
            slots = listOf(
            WidgetSlotDef("Stimmung", "health.mood", null),
            ),
        ),
        WidgetCatalogDef(
            key = "weightTrend",
            title = "Gewicht",
            groupLabel = "Gesundheit",
            accentHex = "#F43F5E",
            template = "stat",
            route = "/health",
            slots = listOf(
            WidgetSlotDef("Gewicht", "health.weightKg", null),
            ),
        ),
        WidgetCatalogDef(
            key = "healthScore",
            title = "Score",
            groupLabel = "Gesundheit",
            accentHex = "#F43F5E",
            template = "stat",
            route = "/health",
            slots = listOf(
            WidgetSlotDef("Score", "health.score", null),
            ),
        ),
        WidgetCatalogDef(
            key = "healthSnapshot",
            title = "Gesundheit",
            groupLabel = "Gesundheit",
            accentHex = "#F43F5E",
            template = "stat",
            route = "/health",
            slots = listOf(
            WidgetSlotDef("Score", "health.score", null),
            ),
        ),
        WidgetCatalogDef(
            key = "activeMinutes",
            title = "Aktive Min.",
            groupLabel = "Gesundheit",
            accentHex = "#F43F5E",
            template = "stat",
            route = "/health",
            slots = listOf(
            WidgetSlotDef("Minuten", "health.activeMinutes", null),
            ),
        ),
        WidgetCatalogDef(
            key = "caloriesBurned",
            title = "Verbrannt",
            groupLabel = "Gesundheit",
            accentHex = "#F43F5E",
            template = "stat",
            route = "/health",
            slots = listOf(
            WidgetSlotDef("kcal", "health.caloriesBurned", null),
            ),
        ),
        WidgetCatalogDef(
            key = "stepsWeekChart",
            title = "Schritte-Woche",
            groupLabel = "Gesundheit",
            accentHex = "#F43F5E",
            template = "stat",
            route = "/health",
            slots = listOf(
            WidgetSlotDef("Ø Schritte", "health.stepsWeekAvg", null),
            ),
        ),
        WidgetCatalogDef(
            key = "weightChart",
            title = "Gewichtsverlauf",
            groupLabel = "Gesundheit",
            accentHex = "#F43F5E",
            template = "stat",
            route = "/health",
            slots = listOf(
            WidgetSlotDef("Gewicht", "health.weightKg", null),
            ),
        ),
        WidgetCatalogDef(
            key = "caloriesRing",
            title = "Kalorien",
            groupLabel = "Ernährung",
            accentHex = "#3DD68C",
            template = "progress",
            route = "/nutrition",
            slots = listOf(
            WidgetSlotDef("Kalorien", "nutrition.kcal", "nutrition.kcalGoal"),
            ),
        ),
        WidgetCatalogDef(
            key = "macros",
            title = "Makros",
            groupLabel = "Ernährung",
            accentHex = "#3DD68C",
            template = "dualStat",
            route = "/nutrition",
            slots = listOf(
            WidgetSlotDef("Protein", "nutrition.protein", null),
            WidgetSlotDef("Kohlenhydrate", "nutrition.carbs", null),
            ),
        ),
        WidgetCatalogDef(
            key = "water",
            title = "Wasser",
            groupLabel = "Ernährung",
            accentHex = "#3DD68C",
            template = "progress",
            route = "/nutrition",
            slots = listOf(
            WidgetSlotDef("Wasser", "nutrition.waterMl", "nutrition.waterGoalMl"),
            ),
        ),
        WidgetCatalogDef(
            key = "lastMeal",
            title = "Letzte Mahlzeit",
            groupLabel = "Ernährung",
            accentHex = "#3DD68C",
            template = "stat",
            route = "/nutrition",
            slots = listOf(
            WidgetSlotDef("Mahlzeit", "nutrition.lastMeal", null),
            ),
        ),
        WidgetCatalogDef(
            key = "remainingCalories",
            title = "Rest-kcal",
            groupLabel = "Ernährung",
            accentHex = "#3DD68C",
            template = "progress",
            route = "/nutrition",
            slots = listOf(
            WidgetSlotDef("Rest", "nutrition.kcal", "nutrition.kcalGoal"),
            ),
        ),
        WidgetCatalogDef(
            key = "supplementsToday",
            title = "Supplements",
            groupLabel = "Ernährung",
            accentHex = "#3DD68C",
            template = "stat",
            route = "/nutrition",
            slots = listOf(
            WidgetSlotDef("Supplements", "nutrition.supplementsToday", null),
            ),
        ),
        WidgetCatalogDef(
            key = "mealsToday",
            title = "Mahlzeiten",
            groupLabel = "Ernährung",
            accentHex = "#3DD68C",
            template = "stat",
            route = "/nutrition",
            slots = listOf(
            WidgetSlotDef("Mahlzeiten", "nutrition.mealsToday", null),
            ),
        ),
        WidgetCatalogDef(
            key = "nextWorkout",
            title = "Nächstes Workout",
            groupLabel = "Training",
            accentHex = "#5B6CF9",
            template = "stat",
            route = "/training",
            slots = listOf(
            WidgetSlotDef("Workout", "training.nextWorkout", null),
            ),
        ),
        WidgetCatalogDef(
            key = "weeklyVolume",
            title = "Wochen-Volumen",
            groupLabel = "Training",
            accentHex = "#5B6CF9",
            template = "stat",
            route = "/training",
            slots = listOf(
            WidgetSlotDef("Sets", "training.weeklyVolume", null),
            ),
        ),
        WidgetCatalogDef(
            key = "muscleHeatmap",
            title = "Muskeln",
            groupLabel = "Training",
            accentHex = "#5B6CF9",
            template = "stat",
            route = "/training",
            slots = listOf(
            WidgetSlotDef("Muskeln", "training.muscleHeatmap", null),
            ),
        ),
        WidgetCatalogDef(
            key = "lastWorkout",
            title = "Letztes Workout",
            groupLabel = "Training",
            accentHex = "#5B6CF9",
            template = "stat",
            route = "/training",
            slots = listOf(
            WidgetSlotDef("Workout", "training.lastWorkout", null),
            ),
        ),
        WidgetCatalogDef(
            key = "trainingStreak",
            title = "Trainings-Streak",
            groupLabel = "Training",
            accentHex = "#5B6CF9",
            template = "stat",
            route = "/training",
            slots = listOf(
            WidgetSlotDef("Wochen", "training.streak", null),
            ),
        ),
        WidgetCatalogDef(
            key = "weeklyWorkouts",
            title = "Wochen-Workouts",
            groupLabel = "Training",
            accentHex = "#5B6CF9",
            template = "stat",
            route = "/training",
            slots = listOf(
            WidgetSlotDef("Workouts", "training.weeklyWorkouts", null),
            ),
        ),
        WidgetCatalogDef(
            key = "personalRecords",
            title = "Rekorde",
            groupLabel = "Training",
            accentHex = "#5B6CF9",
            template = "stat",
            route = "/training",
            slots = listOf(
            WidgetSlotDef("Rekorde", "training.personalRecords", null),
            ),
        ),
        WidgetCatalogDef(
            key = "restTimerQuick",
            title = "Rest-Timer",
            groupLabel = "Training",
            accentHex = "#5B6CF9",
            template = "stat",
            route = "/training",
            slots = listOf(
            WidgetSlotDef("Timer", "training.restTimer", null),
            ),
        ),
        WidgetCatalogDef(
            key = "openTodos",
            title = "Offene Todos",
            groupLabel = "Planung",
            accentHex = "#F5A623",
            template = "stat",
            route = "/planning",
            slots = listOf(
            WidgetSlotDef("Offen", "planning.openTodos", null),
            ),
        ),
        WidgetCatalogDef(
            key = "todayAppointments",
            title = "Heute",
            groupLabel = "Planung",
            accentHex = "#F5A623",
            template = "list",
            route = "/planning",
            slots = listOf(
            WidgetSlotDef("Termin", "planning.nextAppointment", null),
            ),
        ),
        WidgetCatalogDef(
            key = "habitsToday",
            title = "Gewohnheiten",
            groupLabel = "Planung",
            accentHex = "#F5A623",
            template = "progress",
            route = "/planning",
            slots = listOf(
            WidgetSlotDef("Habits", "planning.habitsDone", "planning.habitsTotal"),
            ),
        ),
        WidgetCatalogDef(
            key = "medicationsToday",
            title = "Medikamente",
            groupLabel = "Planung",
            accentHex = "#F5A623",
            template = "progress",
            route = "/planning",
            slots = listOf(
            WidgetSlotDef("Medis", "planning.medsDone", "planning.medsTotal"),
            ),
        ),
        WidgetCatalogDef(
            key = "nextAppointmentCountdown",
            title = "Nächster Termin",
            groupLabel = "Planung",
            accentHex = "#F5A623",
            template = "stat",
            route = "/planning",
            slots = listOf(
            WidgetSlotDef("Termin", "planning.nextAppointment", null),
            ),
        ),
        WidgetCatalogDef(
            key = "overdueTodos",
            title = "Überfällig",
            groupLabel = "Planung",
            accentHex = "#F5A623",
            template = "stat",
            route = "/planning",
            slots = listOf(
            WidgetSlotDef("Überfällig", "planning.overdueTodos", null),
            ),
        ),
        WidgetCatalogDef(
            key = "bestHabitStreak",
            title = "Beste Serie",
            groupLabel = "Planung",
            accentHex = "#F5A623",
            template = "stat",
            route = "/planning",
            slots = listOf(
            WidgetSlotDef("Tage", "planning.bestHabitStreak", null),
            ),
        ),
        WidgetCatalogDef(
            key = "balanceMonth",
            title = "Saldo",
            groupLabel = "Budget",
            accentHex = "#00D4D4",
            template = "stat",
            route = "/budget",
            slots = listOf(
            WidgetSlotDef("Saldo", "budget.balanceMonth", null),
            ),
        ),
        WidgetCatalogDef(
            key = "incomeExpense",
            title = "Ein/Aus",
            groupLabel = "Budget",
            accentHex = "#00D4D4",
            template = "dualStat",
            route = "/budget",
            slots = listOf(
            WidgetSlotDef("Einnahmen", "budget.income", null),
            WidgetSlotDef("Ausgaben", "budget.expense", null),
            ),
        ),
        WidgetCatalogDef(
            key = "budgetProgress",
            title = "Budget",
            groupLabel = "Budget",
            accentHex = "#00D4D4",
            template = "progress",
            route = "/budget",
            slots = listOf(
            WidgetSlotDef("Budget", "budget.spent", "budget.limit"),
            ),
        ),
        WidgetCatalogDef(
            key = "accountsOverview",
            title = "Konten",
            groupLabel = "Budget",
            accentHex = "#00D4D4",
            template = "stat",
            route = "/budget",
            slots = listOf(
            WidgetSlotDef("Konten", "budget.accountsOverview", null),
            ),
        ),
        WidgetCatalogDef(
            key = "topCategory",
            title = "Top-Ausgabe",
            groupLabel = "Budget",
            accentHex = "#00D4D4",
            template = "stat",
            route = "/budget",
            slots = listOf(
            WidgetSlotDef("Kategorie", "budget.topCategory", null),
            ),
        ),
        WidgetCatalogDef(
            key = "recentTransactions",
            title = "Letzte",
            groupLabel = "Budget",
            accentHex = "#00D4D4",
            template = "stat",
            route = "/budget",
            slots = listOf(
            WidgetSlotDef("Transaktion", "budget.recentTransaction", null),
            ),
        ),
        WidgetCatalogDef(
            key = "savingsGoal",
            title = "Sparziel",
            groupLabel = "Budget",
            accentHex = "#00D4D4",
            template = "stat",
            route = "/budget",
            slots = listOf(
            WidgetSlotDef("Ziel", "budget.savingsGoal", null),
            ),
        ),
        WidgetCatalogDef(
            key = "recurringDue",
            title = "Wiederkehrend",
            groupLabel = "Budget",
            accentHex = "#00D4D4",
            template = "stat",
            route = "/budget",
            slots = listOf(
            WidgetSlotDef("Fällig", "budget.recurringDue", null),
            ),
        ),
        WidgetCatalogDef(
            key = "monthTrend",
            title = "Monats-Trend",
            groupLabel = "Budget",
            accentHex = "#00D4D4",
            template = "stat",
            route = "/budget",
            slots = listOf(
            WidgetSlotDef("Trend", "budget.monthTrend", null),
            ),
        ),
        WidgetCatalogDef(
            key = "writeStreak",
            title = "Schreib-Streak",
            groupLabel = "Tagebuch",
            accentHex = "#9B8EC4",
            template = "stat",
            route = "/diary",
            slots = listOf(
            WidgetSlotDef("Tage", "diary.writeStreak", null),
            ),
        ),
        WidgetCatalogDef(
            key = "lastEntry",
            title = "Letzter Eintrag",
            groupLabel = "Tagebuch",
            accentHex = "#9B8EC4",
            template = "stat",
            route = "/diary",
            slots = listOf(
            WidgetSlotDef("Eintrag", "diary.lastEntry", null),
            ),
        ),
        WidgetCatalogDef(
            key = "yearHeatmap",
            title = "Jahres-Heatmap",
            groupLabel = "Tagebuch",
            accentHex = "#9B8EC4",
            template = "stat",
            route = "/diary",
            slots = listOf(
            WidgetSlotDef("Einträge", "diary.yearHeatmap", null),
            ),
        ),
        WidgetCatalogDef(
            key = "moodCalendar",
            title = "Stimmungs-Kalender",
            groupLabel = "Tagebuch",
            accentHex = "#9B8EC4",
            template = "stat",
            route = "/diary",
            slots = listOf(
            WidgetSlotDef("Stimmung", "diary.moodCalendar", null),
            ),
        ),
        WidgetCatalogDef(
            key = "entriesThisMonth",
            title = "Einträge/Monat",
            groupLabel = "Tagebuch",
            accentHex = "#9B8EC4",
            template = "stat",
            route = "/diary",
            slots = listOf(
            WidgetSlotDef("Einträge", "diary.entriesThisMonth", null),
            ),
        ),
        WidgetCatalogDef(
            key = "currentStreak",
            title = "Aktueller Streak",
            groupLabel = "Abstinenz",
            accentHex = "#FFAA55",
            template = "stat",
            route = "/abstinence",
            slots = listOf(
            WidgetSlotDef("Dauer", "abstinence.duration", null),
            ),
        ),
        WidgetCatalogDef(
            key = "longestStreak",
            title = "Längster Streak",
            groupLabel = "Abstinenz",
            accentHex = "#FFAA55",
            template = "stat",
            route = "/abstinence",
            slots = listOf(
            WidgetSlotDef("Tage", "abstinence.longestStreak", null),
            ),
        ),
        WidgetCatalogDef(
            key = "moneySaved",
            title = "Gespart",
            groupLabel = "Abstinenz",
            accentHex = "#FFAA55",
            template = "stat",
            route = "/abstinence",
            slots = listOf(
            WidgetSlotDef("Gespart", "abstinence.moneySaved", null),
            ),
        ),
        WidgetCatalogDef(
            key = "allCounters",
            title = "Alle Counter",
            groupLabel = "Abstinenz",
            accentHex = "#FFAA55",
            template = "stat",
            route = "/abstinence",
            slots = listOf(
            WidgetSlotDef("Counter", "abstinence.allCounters", null),
            ),
        ),
        WidgetCatalogDef(
            key = "lastIntake",
            title = "Letzte Einnahme",
            groupLabel = "Mittel",
            accentHex = "#0099BB",
            template = "stat",
            route = "/substances",
            slots = listOf(
            WidgetSlotDef("Zuletzt", "substances.lastIntake", null),
            ),
        ),
        WidgetCatalogDef(
            key = "takenToday",
            title = "Heute",
            groupLabel = "Mittel",
            accentHex = "#0099BB",
            template = "stat",
            route = "/substances",
            slots = listOf(
            WidgetSlotDef("Heute", "substances.takenToday", null),
            ),
        ),
        WidgetCatalogDef(
            key = "cycleDay",
            title = "Zyklustag",
            groupLabel = "Zyklus",
            accentHex = "#FF8FAB",
            template = "stat",
            route = "/period",
            slots = listOf(
            WidgetSlotDef("Tag", "period.cycleDay", null),
            ),
        ),
        WidgetCatalogDef(
            key = "nextPeriod",
            title = "Nächste Periode",
            groupLabel = "Zyklus",
            accentHex = "#FF8FAB",
            template = "stat",
            route = "/period",
            slots = listOf(
            WidgetSlotDef("Tage", "period.nextDays", null),
            ),
        ),
        WidgetCatalogDef(
            key = "notesCount",
            title = "Notizen",
            groupLabel = "Notizen",
            accentHex = "#9B8EC4",
            template = "stat",
            route = "/notes",
            slots = listOf(
            WidgetSlotDef("Notizen", "notes.count", null),
            ),
        ),
        WidgetCatalogDef(
            key = "lastNote",
            title = "Letzte Notiz",
            groupLabel = "Notizen",
            accentHex = "#9B8EC4",
            template = "stat",
            route = "/notes",
            slots = listOf(
            WidgetSlotDef("Notiz", "notes.lastNote", null),
            ),
        ),
        WidgetCatalogDef(
            key = "pinnedNote",
            title = "Angepinnt",
            groupLabel = "Notizen",
            accentHex = "#9B8EC4",
            template = "stat",
            route = "/notes",
            slots = listOf(
            WidgetSlotDef("Notiz", "notes.pinnedNote", null),
            ),
        ),
        WidgetCatalogDef(
            key = "placesCount",
            title = "Orte",
            groupLabel = "Karte",
            accentHex = "#3DD68C",
            template = "stat",
            route = "/graffitimap",
            slots = listOf(
            WidgetSlotDef("Orte", "map.placesCount", null),
            ),
        ),
        WidgetCatalogDef(
            key = "lastPhoto",
            title = "Letztes Foto",
            groupLabel = "Karte",
            accentHex = "#3DD68C",
            template = "stat",
            route = "/graffitimap",
            slots = listOf(
            WidgetSlotDef("Foto", "map.lastPhoto", null),
            ),
        ),
        WidgetCatalogDef(
            key = "mapPreview",
            title = "Karte",
            groupLabel = "Karte",
            accentHex = "#3DD68C",
            template = "stat",
            route = "/graffitimap",
            slots = listOf(
            WidgetSlotDef("Orte", "map.mapPreview", null),
            ),
        ),
    )
    fun byKey(k: String): WidgetCatalogDef? = (tabs + functions).firstOrNull { it.key == k }
}
